SELECT pais.nome FROM pais;	cnpjPT
SELECT DISTINCT pais.nome FROM estabelecimento JOIN pais ON estabelecimento.codigo_pais = pais.codigo;	cnpjPT
SELECT COUNT(*) FROM empresa;	cnpjPT
SELECT nome FROM cidade;	cnpjPT
SELECT estabelecimento.nome, cidade.nome FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo	cnpjPT
SELECT nome FROM cidade WHERE codigo = 1;	cnpjPT
SELECT nome FROM cidade WHERE codigo < 10;	cnpjPT
SELECT empresa.nome FROM empresa	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa	cnpjPT
SELECT cnpj_basico FROM empresa WHERE capital < 1000;	cnpjPT
SELECT nome FROM empresa WHERE capital = 60000.0;	cnpjPT
SELECT nome FROM empresa WHERE capital > 50000;	cnpjPT
SELECT nome, cnpj_basico FROM empresa WHERE capital > 50000;	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, porte_empresa.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE empresa.capital > 50000;	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE empresa.capital > 50000;	cnpjPT
SELECT nome FROM empresa WHERE capital > 1000000;	cnpjPT
SELECT COUNT(*) FROM empresa WHERE capital > 1000000;	cnpjPT
SELECT SUM(capital) FROM empresa	cnpjPT
SELECT AVG(capital) FROM empresa;	cnpjPT
SELECT codigo_porte_empresa, AVG(capital) FROM empresa GROUP BY codigo_porte_empresa;	cnpjPT
SELECT MAX(capital) FROM empresa;	cnpjPT
SELECT MIN(capital), MAX(capital) FROM empresa;	cnpjPT
SELECT MIN(capital), MAX(capital) FROM empresa WHERE codigo_porte_empresa = 3;	cnpjPT
SELECT SUM(capital) FROM empresa WHERE codigo_porte_empresa = 3;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa ORDER BY empresa.capital DESC LIMIT 10	cnpjPT
SELECT cnpj_basico FROM empresa WHERE capital BETWEEN 1000 AND 10000;	cnpjPT
SELECT capital FROM empresa WHERE cnpj_basico = '02281679';	cnpjPT
SELECT DISTINCT estado FROM estabelecimento;	cnpjPT
SELECT cnpj_basico FROM estabelecimento WHERE estado = 'RN';	cnpjPT
SELECT DISTINCT codigo_cnae_principal FROM estabelecimento WHERE estado = 'SP';	cnpjPT
SELECT COUNT(*) FROM estabelecimento WHERE matriz_ou_filial = '1';	cnpjPT
SELECT DISTINCT estado FROM estabelecimento WHERE matriz_ou_filial = '2';	cnpjPT
SELECT cnpj_basico FROM estabelecimento WHERE codigo_cnae_principal = 5612100;	cnpjPT
SELECT codigo, descricao FROM porte_empresa;	cnpjPT
SELECT descricao, codigo FROM faixa_etaria;	cnpjPT
SELECT descricao FROM tipo_socio;	cnpjPT
SELECT descricao FROM faixa_etaria WHERE codigo = 5;	cnpjPT
SELECT COUNT(DISTINCT nome) FROM cnae;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE natureza_juridica.descricao = 'Órgão Público do Poder Executivo Federal';	cnpjPT
SELECT SUM(empresa.capital) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE descricao = 'MICRO EMPRESA';	cnpjPT
SELECT empresa.nome FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA'	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA';	cnpjPT
SELECT nome FROM empresa WHERE cnpj_basico IN (SELECT cnpj_basico FROM tributacao WHERE opcao_pelo_simples_nacional = 'S');	cnpjPT
SELECT empresa.nome FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN tributacao ON tributacao.cnpj_basico = empresa.cnpj_basico WHERE porte_empresa.descricao = 'MICRO EMPRESA' AND tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, cnae.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, porte_empresa.descricao FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo	cnpjPT
SELECT empresa.nome, empresa.capital, porte_empresa.descricao FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo;	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo;	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao, porte_empresa.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo;	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo ORDER BY empresa.capital DESC;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE natureza_juridica.descricao = 'Órgão Público do Poder Executivo Federal';	cnpjPT
SELECT estabelecimento.nome, estabelecimento.data_inicio_atividade FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT estabelecimento.nome, estabelecimento.data_inicio_atividade FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT nome, data_inicio_atividade FROM estabelecimento WHERE codigo_cidade = 2369;	cnpjPT
SELECT nome, estado FROM estabelecimento WHERE codigo_situacao_cadastral = 1;	cnpjPT
SELECT cnpj_basico FROM estabelecimento WHERE nome LIKE 'S%';	cnpjPT
SELECT codigo FROM cnae WHERE nome LIKE '%Z%';	cnpjPT
SELECT nome FROM empresa ORDER BY capital DESC LIMIT 1;	cnpjPT
SELECT codigo_porte_empresa FROM empresa ORDER BY capital ASC LIMIT 1;	cnpjPT
SELECT cnpj_basico FROM empresa ORDER BY capital DESC LIMIT 3;	cnpjPT
SELECT codigo_porte_empresa, COUNT(*) FROM empresa GROUP BY codigo_porte_empresa;	cnpjPT
SELECT porte_empresa.descricao, COUNT(empresa.cnpj_basico) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo GROUP BY porte_empresa.descricao ORDER BY COUNT(empresa.cnpj_basico) DESC	cnpjPT
SELECT porte_empresa.descricao, COUNT(empresa.cnpj_basico), AVG(empresa.capital) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo GROUP BY porte_empresa.descricao ORDER BY COUNT(empresa.cnpj_basico) DESC	cnpjPT
SELECT porte_empresa.descricao, AVG(empresa.capital) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo GROUP BY porte_empresa.descricao ORDER BY AVG(empresa.capital) DESC	cnpjPT
SELECT estado, COUNT(*) FROM estabelecimento GROUP BY estado;	cnpjPT
SELECT codigo_natureza_juridica, SUM(capital) FROM empresa GROUP BY codigo_natureza_juridica;	cnpjPT
SELECT COUNT(*) FROM estabelecimento JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cnae.nome = 'Serviços de engenharia';	cnpjPT
SELECT estabelecimento.cnpj_basico, situacao_cadastral.descricao FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo	cnpjPT
SELECT DISTINCT empresa.cnpj_basico FROM empresa JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND tributacao.opcao_pelo_mei = 'S';	cnpjPT
SELECT faixa_etaria.descricao, COUNT(socio.codigo_faixa_etaria) FROM socio JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo GROUP BY faixa_etaria.descricao;	cnpjPT
SELECT situacao_cadastral.descricao FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE estabelecimento.cnpj_basico = '02391701';	cnpjPT
SELECT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico WHERE socio.cpf_ou_cnpj = '61204657000165'	cnpjPT
SELECT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico WHERE socio.cpf_ou_cnpj = '***847828**'	cnpjPT
SELECT COUNT(DISTINCT estabelecimento.cnpj_basico) FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE estabelecimento.estado = 'MG' AND situacao_cadastral.descricao = 'ATIVA'	cnpjPT
SELECT count(*) FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE cidade.nome = 'RIO DE JANEIRO' AND estabelecimento.codigo_situacao_cadastral = 1;	cnpjPT
SELECT COUNT(*) FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico WHERE socio.cpf_ou_cnpj = '***004123**';	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao, qualificacao.descricao, porte_empresa.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN qualificacao ON empresa.codigo_qualificacao_responsavel = qualificacao.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE natureza_juridica.descricao = 'Órgão Público do Poder Executivo Federal' AND estabelecimento.data_inicio_atividade > '20140101';	cnpjPT
SELECT estabelecimento.nome, estabelecimento.data_inicio_atividade, cnae.nome FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE empresa.codigo_natureza_juridica > 2000 ORDER BY empresa.nome;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico WHERE socio.codigo_pais = 13 AND empresa.codigo_porte_empresa = 1;	cnpjPT
SELECT estado, COUNT(*) FROM estabelecimento GROUP BY estado ORDER BY COUNT(*) DESC LIMIT 5;	cnpjPT
SELECT COUNT(*) FROM estabelecimento JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cnae.nome LIKE 'Comércio%';	cnpjPT
SELECT porte_empresa.descricao FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo ORDER BY empresa.capital DESC LIMIT 1;	cnpjPT
SELECT estabelecimento.nome, estabelecimento.cnpj_basico FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cidade.nome = 'PARA DE MINAS' AND cnae.nome = 'Instalação e manutenção elétrica'	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN motivo_situacao_cadastral ON estabelecimento.codigo_motivo_situacao_cadastral = motivo_situacao_cadastral.codigo WHERE motivo_situacao_cadastral.descricao = 'OMISSAO DE DECLARACOES'	cnpjPT
SELECT empresa.capital FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo WHERE faixa_etaria.descricao = '21 a 30 anos'	cnpjPT
SELECT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE qualificacao.descricao = 'Administrador';	cnpjPT
SELECT AVG(empresa.capital) FROM empresa JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE tributacao.opcao_pelo_mei = 'S' AND estabelecimento.estado = 'SP';	cnpjPT
SELECT COUNT(*) FROM empresa WHERE capital > (SELECT AVG(capital) FROM empresa)	cnpjPT
SELECT DISTINCT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo WHERE faixa_etaria.descricao = '61 a 70 anos'	cnpjPT
SELECT porte_empresa.descricao, AVG(empresa.capital) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo GROUP BY porte_empresa.descricao HAVING COUNT(empresa.cnpj_basico) > 10 ORDER BY AVG(empresa.capital) DESC;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'DEMAIS' AND estabelecimento.estado = 'SP';	cnpjPT
SELECT socio.nome FROM socio JOIN empresa ON socio.cnpj_basico = empresa.cnpj_basico JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA'	cnpjPT
SELECT empresa.nome FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE porte_empresa.descricao = 'DEMAIS' AND empresa.capital > 1000000 AND estabelecimento.estado = 'SP'	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE porte_empresa.descricao = 'DEMAIS' AND empresa.capital > 50000000	cnpjPT
SELECT DISTINCT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE qualificacao.descricao = 'Administrador'	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, cidade.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'BELO HORIZONTE' AND tributacao.opcao_pelo_simples_nacional = 'S' AND tributacao.opcao_pelo_mei = 'N';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao, empresa.capital, natureza_juridica.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND tipo_socio.descricao = 'PESSOA FÍSICA';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao, tipo_socio.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND tipo_socio.descricao = 'PESSOA FÍSICA';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao, natureza_juridica.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND cidade.nome = 'GUAJARA-MIRIM' AND situacao_cadastral.descricao = 'ATIVA';	cnpjPT
SELECT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND cidade.nome LIKE 'GUA%';	cnpjPT
SELECT empresa.nome, socio.nome, qualificacao.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND faixa_etaria.descricao = '0 a 12 anos' AND natureza_juridica.descricao = 'Sociedade Empresária Limitada';	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN tributacao ON tributacao.cnpj_basico = empresa.cnpj_basico WHERE porte_empresa.descricao = 'MICRO EMPRESA' AND tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, socio.nome, natureza_juridica.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo LEFT JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE empresa.capital > 50000 AND faixa_etaria.descricao = '0 a 12 anos' OR tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, estabelecimento.data_inicio_atividade FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE faixa_etaria.descricao = '0 a 12 anos' AND natureza_juridica.descricao = 'Sociedade Empresária Limitada' AND tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND tipo_socio.descricao = 'PESSOA FÍSICA';	cnpjPT
SELECT empresa.nome, socio.nome, socio.nome_representante_legal, cnae.nome, cidade.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND tipo_socio.descricao = 'PESSOA FÍSICA';	cnpjPT
SELECT empresa.nome, socio.nome, natureza_juridica.descricao, faixa_etaria.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN pais ON socio.codigo_pais = pais.codigo WHERE pais.nome = 'AFEGANISTAO' AND natureza_juridica.descricao != 'Natureza Jurídica não informada';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND cnae.nome = 'Cultivo de arroz';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao, natureza_juridica.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN qualificacao ON socio.codigo_qualificacao_representante_legal = qualificacao.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND qualificacao.descricao = 'Administrador';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE cidade.nome = 'GUAJARA-MIRIM' AND porte_empresa.descricao = 'MICRO EMPRESA';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao, estabelecimento.nome, cidade.nome, cnae.nome, natureza_juridica.descricao, porte_empresa.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND faixa_etaria.descricao = '13 a 20 anos' ORDER BY empresa.nome;	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE empresa.cnpj_basico IN (SELECT cnpj_basico FROM tributacao WHERE opcao_pelo_simples_nacional = 'S');	cnpjPT
SELECT empresa.nome FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN qualificacao ON socio.codigo_qualificacao_representante_legal = qualificacao.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND qualificacao.descricao = 'Pai' AND cidade.nome = 'PINDAMONHANGABA';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE cidade.nome = 'BELO HORIZONTE' AND tipo_socio.descricao = 'PESSOA FÍSICA' AND faixa_etaria.descricao = '0 a 12 anos' AND tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, cnae.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE qualificacao.codigo = 5 AND cidade.codigo = 1;	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, socio.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE cidade.nome = 'GUAJARA-MIRIM' AND tributacao.opcao_pelo_simples_nacional = 'S';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, porte_empresa.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE empresa.capital > 50000 AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico LEFT JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo LEFT JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE socio.codigo_tipo_socio = (SELECT codigo FROM tipo_socio WHERE descricao = 'PESSOA FÍSICA') AND socio.codigo_qualificacao_representante_legal = SELECT codigo FROM qualificacao WHERE descricao = 'Não informada') OR estabelecimento.codigo_cidade = ( SELECT codigo FROM cidade WHERE nome = 'BELO HORIZONTE';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND natureza_juridica.descricao ='Sociedade Empresária Limitada';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE empresa.cnpj_basico IN (SELECT cnpj_basico FROM tributacao WHERE opcao_pelo_simples_nacional = 'S');	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, cnae.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, qualificacao.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN qualificacao ON empresa.codigo_qualificacao_responsavel = qualificacao.codigo JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico WHERE cidade.nome = 'GUAJARA-MIRIM' AND tributacao.opcao_pelo_simples_nacional = 'S' AND tributacao.opcao_pelo_mei = 'N';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA' ORDER BY empresa.nome;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA' AND faixa_etaria.descricao = '0 a 12 anos';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, porte_empresa.descricao, cnae.nome, tipo_socio.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE cidade.nome = 'GUAJARA-MIRIM' AND porte_empresa.descricao = 'MICRO EMPRESA';	cnpjPT
SELECT empresa.nome, empresa.capital, socio.nome, socio.nome_representante_legal, faixa_etaria.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo LEFT JOIN qualificacao ON socio.codigo_qualificacao_representante_legal = qualificacao.codigo LEFT JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND qualificacao.descricao != 'Não informada' OR qualificacao.descricao = 'Administrador' ORDER BY empresa.capital DESC;	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND porte_empresa.descricao = 'MICRO EMPRESA';	cnpjPT
SELECT empresa.nome, faixa_etaria.descricao, cidade.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE situacao_cadastral.descricao = 'ATIVA' AND cidade.nome = 'PINDAMONHANGABA' AND cnae.nome = 'Cultivo de arroz';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON estabelecimento.cnpj_basico = tributacao.cnpj_basico WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND natureza_juridica.descricao != 'Natureza Jurídica não informada';	cnpjPT
SELECT empresa.nome, empresa.capital, natureza_juridica.descricao FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo JOIN qualificacao ON socio.codigo_qualificacao_representante_legal = qualificacao.codigo JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND qualificacao.descricao = 'Administrador' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE faixa_etaria.descricao = '0 a 12 anos' AND cidade.nome = 'GUAJARA-MIRIM';	cnpjPT
SELECT empresa.nome, socio.nome, faixa_etaria.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN faixa_etaria ON socio.codigo_faixa_etaria = faixa_etaria.codigo JOIN tipo_socio ON socio.codigo_tipo_socio = tipo_socio.codigo WHERE tipo_socio.descricao = 'PESSOA FÍSICA' AND faixa_etaria.descricao = '13 a 20 anos';	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao, porte_empresa.descricao FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE empresa.capital > 50000 AND cidade.nome = 'ALTO ALEGRE DOS PARECIS';	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE cidade.nome = 'GUAJARA-MIRIM' AND situacao_cadastral.descricao = 'ATIVA';	cnpjPT
SELECT cnae.nome FROM estabelecimento JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo GROUP BY cnae.nome ORDER BY COUNT(*) DESC LIMIT 1;	cnpjPT
SELECT cidade.nome FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo GROUP BY cidade.nome ORDER BY COUNT(*) DESC LIMIT 5;	cnpjPT
SELECT estabelecimento.nome, estabelecimento.cnpj_basico FROM estabelecimento JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE estabelecimento.estado = 'MG' AND cnae.nome = 'Construção de edifícios'	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE estabelecimento.estado = 'SP' AND empresa.capital > 1000000;	cnpjPT
SELECT empresa.capital FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE estabelecimento.estado = 'GO' GROUP BY empresa.nome, empresa.cnpj_basico HAVING COUNT(socio.cnpj_basico) > 5	cnpjPT
SELECT empresa.cnpj_basico FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE empresa.capital > 50000 AND cidade.nome = 'SAO PAULO' EXCEPT SELECT empresa.cnpj_basico FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cnae.nome = 'Construção de edifícios'	cnpjPT
SELECT empresa.cnpj_basico FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE natureza_juridica.descricao = 'Empresário (Individual)' UNION SELECT empresa.cnpj_basico FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo WHERE natureza_juridica.descricao = 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras'	cnpjPT
SELECT pais.nome FROM pais JOIN estabelecimento ON pais.codigo = estabelecimento.codigo_pais JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'EMPRESA PEQUENO PORTE' INTERSECT SELECT pais.nome FROM pais JOIN estabelecimento ON pais.codigo = estabelecimento.codigo_pais JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico WHERE empresa.capital > 1000000;	cnpjPT
SELECT empresa.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE estabelecimento.codigo_cidade = (SELECT codigo FROM cidade WHERE nome = 'PIRAJUI') AND empresa.codigo_porte_empresa = (SELECT codigo FROM porte_empresa WHERE descricao = 'MICRO EMPRESA');	cnpjPT
SELECT AVG(empresa.capital) FROM estabelecimento JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico WHERE estabelecimento.codigo_cidade = (SELECT codigo FROM cidade WHERE nome = 'UMBUZEIRO') AND empresa.codigo_natureza_juridica = (SELECT codigo FROM natureza_juridica WHERE descricao = 'Empresário (Individual)') AND empresa.codigo_porte_empresa = (SELECT codigo FROM porte_empresa WHERE descricao = 'MICRO EMPRESA')	cnpjPT
SELECT count(*) FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico WHERE estabelecimento.codigo_situacao_cadastral = 1 AND empresa.codigo_natureza_juridica = (SELECT codigo FROM natureza_juridica WHERE descricao = 'Empresário (Individual)') AND codigo_cidade = (SELECT codigo FROM cidade WHERE nome = 'RIO DE JANEIRO');	cnpjPT
SELECT estabelecimento.estado, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY estabelecimento.estado HAVING COUNT(estabelecimento.cnpj_basico) > 100 ORDER BY COUNT(estabelecimento.cnpj_basico) DESC	cnpjPT
SELECT natureza_juridica.descricao, AVG(empresa.capital) FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo GROUP BY natureza_juridica.descricao ORDER BY AVG(empresa.capital) DESC LIMIT 5	cnpjPT
SELECT empresa.nome, empresa.capital, situacao_cadastral.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' ORDER BY empresa.capital DESC LIMIT 5	cnpjPT
SELECT natureza_juridica.descricao, SUM(empresa.capital) FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY natureza_juridica.descricao ORDER BY SUM(empresa.capital) DESC LIMIT 5	cnpjPT
SELECT natureza_juridica.descricao, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY natureza_juridica.descricao ORDER BY COUNT(estabelecimento.cnpj_basico) DESC	cnpjPT
SELECT empresa.nome, natureza_juridica.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE empresa.capital > 5000000 AND estabelecimento.estado = 'SP' AND situacao_cadastral.descricao = 'ATIVA'	cnpjPT
SELECT cnae.nome, AVG(empresa.capital) FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE estabelecimento.data_inicio_atividade > '20151231' AND estabelecimento.cnpj_basico IN (SELECT DISTINCT socio.cnpj_basico FROM socio JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE qualificacao.descricao = 'Administrador') GROUP BY cnae.nome HAVING COUNT(DISTINCT empresa.cnpj_basico) > 3 ORDER BY AVG(empresa.capital) DESC	cnpjPT
SELECT cidade.nome, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE estabelecimento.data_inicio_atividade >= '20210101' GROUP BY cidade.nome ORDER BY COUNT(estabelecimento.cnpj_basico) DESC LIMIT 5	cnpjPT
SELECT empresa.nome, cnae.nome, motivo_situacao_cadastral.descricao FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN motivo_situacao_cadastral ON estabelecimento.codigo_motivo_situacao_cadastral = motivo_situacao_cadastral.codigo WHERE estabelecimento.estado = 'SP'	cnpjPT
SELECT cnae.nome, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo GROUP BY cnae.nome ORDER BY COUNT(estabelecimento.cnpj_basico) DESC LIMIT 5	cnpjPT
SELECT qualificacao.descricao, COUNT(socio.cnpj_basico), AVG(empresa.capital) FROM socio JOIN empresa ON socio.cnpj_basico = empresa.cnpj_basico JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo GROUP BY qualificacao.descricao HAVING COUNT(socio.cnpj_basico) >= 10 ORDER BY COUNT(socio.cnpj_basico) DESC	cnpjPT
SELECT natureza_juridica.descricao, COUNT(*) FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'DEMAIS' GROUP BY natureza_juridica.descricao ORDER BY COUNT(*) DESC LIMIT 5	cnpjPT
SELECT porte_empresa.descricao, AVG(empresa.capital) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY porte_empresa.descricao	cnpjPT
SELECT empresa.nome, cnae.nome FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN tributacao ON empresa.cnpj_basico = tributacao.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE tributacao.opcao_pelo_simples_nacional = 'S' AND estabelecimento.data_inicio_atividade > '20151231'	cnpjPT
SELECT estabelecimento.estado, COUNT(*) FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY estabelecimento.estado ORDER BY COUNT(*) DESC LIMIT 5	cnpjPT
SELECT empresa.nome, COUNT(*) FROM empresa JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo WHERE qualificacao.descricao = 'Administrador' GROUP BY empresa.nome	cnpjPT
SELECT natureza_juridica.descricao, AVG(empresa.capital) FROM empresa JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo GROUP BY natureza_juridica.descricao ORDER BY AVG(empresa.capital) DESC LIMIT 5	cnpjPT
SELECT empresa.nome, empresa.capital FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo WHERE porte_empresa.descricao = 'MICRO EMPRESA' ORDER BY empresa.capital DESC LIMIT 5	cnpjPT
SELECT qualificacao.descricao, COUNT(socio.cnpj_basico) FROM socio JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo GROUP BY qualificacao.descricao ORDER BY COUNT(socio.cnpj_basico) DESC LIMIT 5	cnpjPT
SELECT natureza_juridica.descricao, COUNT(empresa.cnpj_basico) FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN natureza_juridica ON empresa.codigo_natureza_juridica = natureza_juridica.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY natureza_juridica.descricao ORDER BY COUNT(empresa.cnpj_basico) DESC	cnpjPT
SELECT empresa.nome, COUNT(socio.cpf_ou_cnpj) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN socio ON empresa.cnpj_basico = socio.cnpj_basico WHERE porte_empresa.descricao = 'MICRO EMPRESA' GROUP BY empresa.nome ORDER BY COUNT(socio.cpf_ou_cnpj) DESC	cnpjPT
SELECT porte_empresa.descricao, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo WHERE situacao_cadastral.descricao = 'ATIVA' GROUP BY porte_empresa.descricao ORDER BY COUNT(estabelecimento.cnpj_basico) DESC	cnpjPT
SELECT cnae.nome, COUNT(empresa.cnpj_basico), AVG(empresa.capital) FROM empresa JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE empresa.cnpj_basico IN (SELECT DISTINCT socio.cnpj_basico FROM socio JOIN qualificacao ON socio.codigo_qualificacao_socio = qualificacao.codigo JOIN estabelecimento ON socio.cnpj_basico = estabelecimento.cnpj_basico JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo JOIN tributacao ON socio.cnpj_basico = tributacao.cnpj_basico WHERE qualificacao.descricao = 'Sócio-Administrador' AND situacao_cadastral.descricao = 'ATIVA' AND tributacao.opcao_pelo_simples_nacional = 'S') GROUP BY cnae.nome HAVING COUNT(empresa.cnpj_basico) > 5 ORDER BY COUNT(empresa.cnpj_basico) DESC	cnpjPT
SELECT porte_empresa.descricao, COUNT(socio.cnpj_basico) FROM socio JOIN empresa ON socio.cnpj_basico = empresa.cnpj_basico JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo GROUP BY porte_empresa.descricao ORDER BY COUNT(socio.cnpj_basico) DESC	cnpjPT
SELECT cidade.nome, COUNT(*) FROM empresa JOIN porte_empresa ON empresa.codigo_porte_empresa = porte_empresa.codigo JOIN estabelecimento ON empresa.cnpj_basico = estabelecimento.cnpj_basico JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo WHERE porte_empresa.descricao = 'DEMAIS' GROUP BY cidade.nome ORDER BY COUNT(*) DESC LIMIT 5	cnpjPT
SELECT cidade.nome, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo GROUP BY cidade.nome ORDER BY COUNT(estabelecimento.cnpj_basico) DESC LIMIT 5	cnpjPT
SELECT cnae.nome, COUNT(DISTINCT estabelecimento.cnpj_basico), SUM(empresa.capital), COUNT(DISTINCT socio.cpf_ou_cnpj) FROM estabelecimento JOIN situacao_cadastral ON estabelecimento.codigo_situacao_cadastral = situacao_cadastral.codigo JOIN socio ON estabelecimento.cnpj_basico = socio.cnpj_basico JOIN pais ON socio.codigo_pais = pais.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo JOIN empresa ON estabelecimento.cnpj_basico = empresa.cnpj_basico WHERE situacao_cadastral.descricao = 'ATIVA' AND pais.nome != 'BRASIL' GROUP BY cnae.nome ORDER BY COUNT(DISTINCT estabelecimento.cnpj_basico) DESC LIMIT 3	cnpjPT
SELECT cnae.nome, COUNT(estabelecimento.cnpj_basico) FROM estabelecimento JOIN cidade ON estabelecimento.codigo_cidade = cidade.codigo JOIN cnae ON estabelecimento.codigo_cnae_principal = cnae.codigo WHERE cidade.nome = 'CURITIBA' GROUP BY cnae.nome ORDER BY COUNT(estabelecimento.cnpj_basico) DESC LIMIT 3	cnpjPT
