SELECT country.name FROM country;	cnpjEN
SELECT DISTINCT country.name FROM establishment JOIN country ON establishment.country_code = country.code;	cnpjEN
SELECT COUNT(*) FROM company;	cnpjEN
SELECT name FROM city;	cnpjEN
SELECT establishment.name, city.name FROM establishment JOIN city ON establishment.city_code = city.code	cnpjEN
SELECT name FROM city WHERE code = 1;	cnpjEN
SELECT name FROM city WHERE code < 10;	cnpjEN
SELECT company.name FROM company	cnpjEN
SELECT company.name, company.capital FROM company	cnpjEN
SELECT company.name, company.capital FROM company	cnpjEN
SELECT basic_cnpj FROM company WHERE capital < 1000;	cnpjEN
SELECT name FROM company WHERE capital = 60000.0;	cnpjEN
SELECT name FROM company WHERE capital > 50000;	cnpjEN
SELECT name, basic_cnpj FROM company WHERE capital > 50000;	cnpjEN
SELECT company.name, legal_nature.description, company_size.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code WHERE company.capital > 50000;	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE company.capital > 50000;	cnpjEN
SELECT name FROM company WHERE capital > 1000000;	cnpjEN
SELECT COUNT(*) FROM company WHERE capital > 1000000;	cnpjEN
SELECT SUM(capital) FROM company	cnpjEN
SELECT AVG(capital) FROM company;	cnpjEN
SELECT company_size_code, AVG(capital) FROM company GROUP BY company_size_code;	cnpjEN
SELECT MAX(capital) FROM company;	cnpjEN
SELECT MIN(capital), MAX(capital) FROM company;	cnpjEN
SELECT MIN(capital), MAX(capital) FROM company WHERE company_size_code = 3;	cnpjEN
SELECT SUM(capital) FROM company WHERE company_size_code = 3;	cnpjEN
SELECT company.name, company.capital FROM company ORDER BY company.capital DESC LIMIT 10	cnpjEN
SELECT basic_cnpj FROM company WHERE capital BETWEEN 1000 AND 10000;	cnpjEN
SELECT capital FROM company WHERE basic_cnpj = '02281679';	cnpjEN
SELECT DISTINCT state FROM establishment;	cnpjEN
SELECT basic_cnpj FROM establishment WHERE state = 'RN';	cnpjEN
SELECT DISTINCT primary_cnae_code FROM establishment WHERE state = 'SP';	cnpjEN
SELECT COUNT(*) FROM establishment WHERE main_or_branch = '1';	cnpjEN
SELECT DISTINCT state FROM establishment WHERE main_or_branch = '2';	cnpjEN
SELECT basic_cnpj FROM establishment WHERE primary_cnae_code = 5612100;	cnpjEN
SELECT code, description FROM company_size;	cnpjEN
SELECT description, code FROM age_range;	cnpjEN
SELECT description FROM partner_type;	cnpjEN
SELECT description FROM age_range WHERE code = 5;	cnpjEN
SELECT COUNT(DISTINCT name) FROM cnae;	cnpjEN
SELECT company.name, company.capital FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE legal_nature.description = 'Órgão Público do Poder Executivo Federal';	cnpjEN
SELECT SUM(company.capital) FROM company JOIN company_size ON company.company_size_code = company_size.code WHERE description = 'MICRO EMPRESA';	cnpjEN
SELECT company.name FROM company JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'MICRO EMPRESA'	cnpjEN
SELECT company.name, company.capital FROM company JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'MICRO EMPRESA';	cnpjEN
SELECT name FROM company WHERE basic_cnpj IN (SELECT basic_cnpj FROM taxation WHERE option_for_simples_taxation = 'S');	cnpjEN
SELECT company.name FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN taxation ON taxation.basic_cnpj = company.basic_cnpj WHERE company_size.description = 'MICRO EMPRESA' AND taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, cnae.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, company_size.description FROM company JOIN company_size ON company.company_size_code = company_size.code	cnpjEN
SELECT company.name, company.capital, company_size.description FROM company JOIN company_size ON company.company_size_code = company_size.code;	cnpjEN
SELECT company.name, company.capital, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code;	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code	cnpjEN
SELECT company.name, company.capital, legal_nature.description, company_size.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code;	cnpjEN
SELECT company.name, company.capital, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code ORDER BY company.capital DESC;	cnpjEN
SELECT company.name, company.capital FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE legal_nature.description = 'Órgão Público do Poder Executivo Federal';	cnpjEN
SELECT establishment.name, establishment.start_activity_date FROM establishment JOIN city ON establishment.city_code = city.code WHERE city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT establishment.name, establishment.start_activity_date FROM establishment JOIN city ON establishment.city_code = city.code WHERE city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT name, start_activity_date FROM establishment WHERE city_code = 2369;	cnpjEN
SELECT name, state FROM establishment WHERE registration_status_code = 1;	cnpjEN
SELECT basic_cnpj FROM establishment WHERE name LIKE 'S%';	cnpjEN
SELECT code FROM cnae WHERE name LIKE '%Z%';	cnpjEN
SELECT name FROM company ORDER BY capital DESC LIMIT 1;	cnpjEN
SELECT company_size_code FROM company ORDER BY capital ASC LIMIT 1;	cnpjEN
SELECT basic_cnpj FROM company ORDER BY capital DESC LIMIT 3;	cnpjEN
SELECT company_size_code, COUNT(*) FROM company GROUP BY company_size_code;	cnpjEN
SELECT company_size.description, COUNT(company.basic_cnpj) FROM company JOIN company_size ON company.company_size_code = company_size.code GROUP BY company_size.description ORDER BY COUNT(company.basic_cnpj) DESC	cnpjEN
SELECT company_size.description, COUNT(company.basic_cnpj), AVG(company.capital) FROM company JOIN company_size ON company.company_size_code = company_size.code GROUP BY company_size.description ORDER BY COUNT(company.basic_cnpj) DESC	cnpjEN
SELECT company_size.description, AVG(company.capital) FROM company JOIN company_size ON company.company_size_code = company_size.code GROUP BY company_size.description ORDER BY AVG(company.capital) DESC	cnpjEN
SELECT state, COUNT(*) FROM establishment GROUP BY state;	cnpjEN
SELECT legal_nature_code, SUM(capital) FROM company GROUP BY legal_nature_code;	cnpjEN
SELECT COUNT(*) FROM establishment JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE cnae.name = 'Serviços de engenharia';	cnpjEN
SELECT establishment.basic_cnpj, registration_status.description FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code	cnpjEN
SELECT DISTINCT company.basic_cnpj FROM company JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S' AND taxation.option_for_mei_taxation = 'S';	cnpjEN
SELECT age_range.description, COUNT(partner.age_range_code) FROM partner JOIN age_range ON partner.age_range_code = age_range.code GROUP BY age_range.description;	cnpjEN
SELECT registration_status.description FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE establishment.basic_cnpj = '02391701';	cnpjEN
SELECT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj WHERE partner.cpf_or_cnpj = '61204657000165'	cnpjEN
SELECT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj WHERE partner.cpf_or_cnpj = '***847828**'	cnpjEN
SELECT COUNT(DISTINCT establishment.basic_cnpj) FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE establishment.state = 'MG' AND registration_status.description = 'ATIVA'	cnpjEN
SELECT count(*) FROM establishment JOIN city ON establishment.city_code = city.code WHERE city.name = 'RIO DE JANEIRO' AND establishment.registration_status_code = 1;	cnpjEN
SELECT COUNT(*) FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj WHERE partner.cpf_or_cnpj = '***004123**';	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, company.capital, legal_nature.description, qualification.description, company_size.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN qualification ON company.responsible_qualification_code = qualification.code JOIN company_size ON company.company_size_code = company_size.code;	cnpjEN
SELECT company.name, company.capital FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE legal_nature.description = 'Órgão Público do Poder Executivo Federal' AND establishment.start_activity_date > '20140101';	cnpjEN
SELECT establishment.name, establishment.start_activity_date, cnae.name FROM establishment JOIN city ON establishment.city_code = city.code JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE company.legal_nature_code > 2000 ORDER BY company.name;	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj WHERE partner.country_code = 13 AND company.company_size_code = 1;	cnpjEN
SELECT state, COUNT(*) FROM establishment GROUP BY state ORDER BY COUNT(*) DESC LIMIT 5;	cnpjEN
SELECT COUNT(*) FROM establishment JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE cnae.name LIKE 'Comércio%';	cnpjEN
SELECT company_size.description FROM company JOIN company_size ON company.company_size_code = company_size.code ORDER BY company.capital DESC LIMIT 1;	cnpjEN
SELECT establishment.name, establishment.basic_cnpj FROM establishment JOIN city ON establishment.city_code = city.code JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE city.name = 'PARA DE MINAS' AND cnae.name = 'Instalação e manutenção elétrica'	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN registration_status_reason ON establishment.registration_status_reason_code = registration_status_reason.code WHERE registration_status_reason.description = 'OMISSAO DE DECLARACOES'	cnpjEN
SELECT company.capital FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code WHERE age_range.description = '21 a 30 anos'	cnpjEN
SELECT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE qualification.description = 'Administrador';	cnpjEN
SELECT AVG(company.capital) FROM company JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE taxation.option_for_mei_taxation = 'S' AND establishment.state = 'SP';	cnpjEN
SELECT COUNT(*) FROM company WHERE capital > (SELECT AVG(capital) FROM company)	cnpjEN
SELECT DISTINCT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code WHERE age_range.description = '61 a 70 anos'	cnpjEN
SELECT company_size.description, AVG(company.capital) FROM company JOIN company_size ON company.company_size_code = company_size.code GROUP BY company_size.description HAVING COUNT(company.basic_cnpj) > 10 ORDER BY AVG(company.capital) DESC;	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'DEMAIS' AND establishment.state = 'SP';	cnpjEN
SELECT partner.name FROM partner JOIN company ON partner.basic_cnpj = company.basic_cnpj JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'MICRO EMPRESA'	cnpjEN
SELECT company.name FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE company_size.description = 'DEMAIS' AND company.capital > 1000000 AND establishment.state = 'SP'	cnpjEN
SELECT company.name, company.capital, legal_nature.description FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE company_size.description = 'DEMAIS' AND company.capital > 50000000	cnpjEN
SELECT DISTINCT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE qualification.description = 'Administrador'	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, city.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN age_range ON partner.age_range_code = age_range.code JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE age_range.description = '0 a 12 anos' AND city.name = 'BELO HORIZONTE' AND taxation.option_for_simples_taxation = 'S' AND taxation.option_for_mei_taxation = 'N';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE taxation.option_for_simples_taxation = 'S' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, age_range.description, company.capital, legal_nature.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE age_range.description = '0 a 12 anos' AND partner_type.description = 'PESSOA FÍSICA';	cnpjEN
SELECT company.name, partner.name, age_range.description, partner_type.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE age_range.description = '0 a 12 anos' AND partner_type.description = 'PESSOA FÍSICA';	cnpjEN
SELECT company.name, partner.name, age_range.description, legal_nature.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN age_range ON partner.age_range_code = age_range.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN city ON establishment.city_code = city.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE partner_type.description = 'PESSOA FÍSICA' AND city.name = 'GUAJARA-MIRIM' AND registration_status.description = 'ATIVA';	cnpjEN
SELECT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE partner_type.description = 'PESSOA FÍSICA' AND city.name LIKE 'GUA%';	cnpjEN
SELECT company.name, partner.name, qualification.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN qualification ON partner.partner_qualification_code = qualification.code JOIN age_range ON partner.age_range_code = age_range.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE partner_type.description = 'PESSOA FÍSICA' AND age_range.description = '0 a 12 anos' AND legal_nature.description = 'Sociedade Empresária Limitada';	cnpjEN
SELECT company.name, company.capital, legal_nature.description FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN taxation ON taxation.basic_cnpj = company.basic_cnpj WHERE company_size.description = 'MICRO EMPRESA' AND taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, partner.name, legal_nature.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN age_range ON partner.age_range_code = age_range.code LEFT JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE company.capital > 50000 AND age_range.description = '0 a 12 anos' OR taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, establishment.start_activity_date FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE age_range.description = '0 a 12 anos' AND legal_nature.description = 'Sociedade Empresária Limitada' AND taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE age_range.description = '0 a 12 anos' AND partner_type.description = 'PESSOA FÍSICA';	cnpjEN
SELECT company.name, partner.name, partner.legal_representative_name, cnae.name, city.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN city ON establishment.city_code = city.code JOIN age_range ON partner.age_range_code = age_range.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE age_range.description = '0 a 12 anos' AND partner_type.description = 'PESSOA FÍSICA';	cnpjEN
SELECT company.name, partner.name, legal_nature.description, age_range.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN age_range ON partner.age_range_code = age_range.code JOIN country ON partner.country_code = country.code WHERE country.name = 'AFEGANISTAO' AND legal_nature.description != 'Natureza Jurídica não informada';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE taxation.option_for_simples_taxation = 'S' AND cnae.name = 'Cultivo de arroz';	cnpjEN
SELECT company.name, partner.name, age_range.description, legal_nature.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN qualification ON partner.legal_representative_qualification_code = qualification.code WHERE partner_type.description = 'PESSOA FÍSICA' AND qualification.description = 'Administrador';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN company_size ON company.company_size_code = company_size.code WHERE city.name = 'GUAJARA-MIRIM' AND company_size.description = 'MICRO EMPRESA';	cnpjEN
SELECT company.name, partner.name, age_range.description, establishment.name, city.name, cnae.name, legal_nature.description, company_size.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE partner_type.description = 'PESSOA FÍSICA' AND age_range.description = '13 a 20 anos' ORDER BY company.name;	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE company.basic_cnpj IN (SELECT basic_cnpj FROM taxation WHERE option_for_simples_taxation = 'S');	cnpjEN
SELECT company.name FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN qualification ON partner.legal_representative_qualification_code = qualification.code JOIN age_range ON partner.age_range_code = age_range.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE partner_type.description = 'PESSOA FÍSICA' AND qualification.description = 'Pai' AND city.name = 'PINDAMONHANGABA';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN age_range ON partner.age_range_code = age_range.code JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE city.name = 'BELO HORIZONTE' AND partner_type.description = 'PESSOA FÍSICA' AND age_range.description = '0 a 12 anos' AND taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, cnae.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE qualification.code = 5 AND city.code = 1;	cnpjEN
SELECT company.name, legal_nature.description, partner.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE city.name = 'GUAJARA-MIRIM' AND taxation.option_for_simples_taxation = 'S';	cnpjEN
SELECT company.name, legal_nature.description, company_size.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE company.capital > 50000 AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE partner.partner_type_code = (SELECT code FROM partner_type WHERE description = 'PESSOA FÍSICA') AND partner.legal_representative_qualification_code = (SELECT code FROM qualification WHERE description = 'Não informada') OR establishment.city_code = (SELECT code FROM city WHERE name = 'BELO HORIZONTE');	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE age_range.description = '0 a 12 anos' AND legal_nature.description ='Sociedade Empresária Limitada';	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE company.basic_cnpj IN (SELECT basic_cnpj FROM taxation WHERE option_for_simples_taxation = 'S');	cnpjEN
SELECT company.name, legal_nature.description, cnae.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, legal_nature.description, qualification.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN qualification ON company.responsible_qualification_code = qualification.code JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj WHERE city.name = 'GUAJARA-MIRIM' AND taxation.option_for_simples_taxation = 'S' AND taxation.option_for_mei_taxation = 'N';	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'MICRO EMPRESA' ORDER BY company.name;	cnpjEN
SELECT company.name, company.capital FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code WHERE company_size.description = 'MICRO EMPRESA' AND age_range.description = '0 a 12 anos';	cnpjEN
SELECT company.name, legal_nature.description, company_size.description, cnae.name, partner_type.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN company_size ON company.company_size_code = company_size.code WHERE city.name = 'GUAJARA-MIRIM' AND company_size.description = 'MICRO EMPRESA';	cnpjEN
SELECT company.name, company.capital, partner.name, partner.legal_representative_name, age_range.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN age_range ON partner.age_range_code = age_range.code LEFT JOIN qualification ON partner.legal_representative_qualification_code = qualification.code LEFT JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE partner_type.description = 'PESSOA FÍSICA' AND qualification.description != 'Não informada' OR qualification.description = 'Administrador' ORDER BY company.capital DESC;	cnpjEN
SELECT company.name, company.capital FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S' AND company_size.description = 'MICRO EMPRESA';	cnpjEN
SELECT company.name, age_range.description, city.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN registration_status ON establishment.registration_status_code = registration_status.code JOIN city ON establishment.city_code = city.code JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE registration_status.description = 'ATIVA' AND city.name = 'PINDAMONHANGABA' AND cnae.name = 'Cultivo de arroz';	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON establishment.basic_cnpj = taxation.basic_cnpj WHERE taxation.option_for_simples_taxation = 'S' AND legal_nature.description != 'Natureza Jurídica não informada';	cnpjEN
SELECT company.name, company.capital, legal_nature.description FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN partner_type ON partner.partner_type_code = partner_type.code JOIN qualification ON partner.legal_representative_qualification_code = qualification.code JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE partner_type.description = 'PESSOA FÍSICA' AND qualification.description = 'Administrador' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN city ON establishment.city_code = city.code WHERE age_range.description = '0 a 12 anos' AND city.name = 'GUAJARA-MIRIM';	cnpjEN
SELECT company.name, partner.name, age_range.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN age_range ON partner.age_range_code = age_range.code JOIN partner_type ON partner.partner_type_code = partner_type.code WHERE partner_type.description = 'PESSOA FÍSICA' AND age_range.description = '13 a 20 anos';	cnpjEN
SELECT company.name, legal_nature.description, company_size.description FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE company.capital > 50000 AND city.name = 'ALTO ALEGRE DOS PARECIS';	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE city.name = 'GUAJARA-MIRIM' AND registration_status.description = 'ATIVA';	cnpjEN
SELECT cnae.name FROM establishment JOIN cnae ON establishment.primary_cnae_code = cnae.code GROUP BY cnae.name ORDER BY COUNT(*) DESC LIMIT 1;	cnpjEN
SELECT city.name FROM establishment JOIN city ON establishment.city_code = city.code GROUP BY city.name ORDER BY COUNT(*) DESC LIMIT 5;	cnpjEN
SELECT establishment.name, establishment.basic_cnpj FROM establishment JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE establishment.state = 'MG' AND cnae.name = 'Construção de edifícios'	cnpjEN
SELECT company.name, company.capital FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE establishment.state = 'SP' AND company.capital > 1000000;	cnpjEN
SELECT company.capital FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE establishment.state = 'GO' GROUP BY company.name, company.basic_cnpj HAVING COUNT(partner.basic_cnpj) > 5	cnpjEN
SELECT company.basic_cnpj FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE company.capital > 50000 AND city.name = 'SAO PAULO' EXCEPT SELECT company.basic_cnpj FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE cnae.name = 'Construção de edifícios'	cnpjEN
SELECT company.basic_cnpj FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE legal_nature.description = 'Empresário (Individual)' UNION SELECT company.basic_cnpj FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code WHERE legal_nature.description = 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras'	cnpjEN
SELECT country.name FROM country JOIN establishment ON country.code = establishment.country_code JOIN company ON establishment.basic_cnpj = company.basic_cnpj JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'EMPRESA PEQUENO PORTE' INTERSECT SELECT country.name FROM country JOIN establishment ON country.code = establishment.country_code JOIN company ON establishment.basic_cnpj = company.basic_cnpj WHERE company.capital > 1000000;	cnpjEN
SELECT company.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE establishment.city_code = (SELECT code FROM city WHERE name = 'PIRAJUI') AND company.company_size_code = (SELECT code FROM company_size WHERE description = 'MICRO EMPRESA');	cnpjEN
SELECT AVG(company.capital) FROM establishment JOIN company ON establishment.basic_cnpj = company.basic_cnpj WHERE establishment.city_code = (SELECT code FROM city WHERE name = 'UMBUZEIRO') AND company.legal_nature_code = (SELECT code FROM legal_nature WHERE description = 'Empresário (Individual)') AND company.company_size_code = (SELECT code FROM company_size WHERE description = 'MICRO EMPRESA')	cnpjEN
SELECT count(*) FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj WHERE establishment.registration_status_code = 1 AND company.legal_nature_code = (SELECT code FROM legal_nature WHERE description = 'Empresário (Individual)') AND city_code = (SELECT code FROM city WHERE name = 'RIO DE JANEIRO');	cnpjEN
SELECT establishment.state, COUNT(establishment.basic_cnpj) FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY establishment.state HAVING COUNT(establishment.basic_cnpj) > 100 ORDER BY COUNT(establishment.basic_cnpj) DESC	cnpjEN
SELECT legal_nature.description, AVG(company.capital) FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code GROUP BY legal_nature.description ORDER BY AVG(company.capital) DESC LIMIT 5	cnpjEN
SELECT company.name, company.capital, registration_status.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' ORDER BY company.capital DESC LIMIT 5	cnpjEN
SELECT legal_nature.description, SUM(company.capital) FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY legal_nature.description ORDER BY SUM(company.capital) DESC LIMIT 5	cnpjEN
SELECT legal_nature.description, COUNT(establishment.basic_cnpj) FROM establishment JOIN company ON establishment.basic_cnpj = company.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY legal_nature.description ORDER BY COUNT(establishment.basic_cnpj) DESC	cnpjEN
SELECT company.name, legal_nature.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE company.capital > 5000000 AND establishment.state = 'SP' AND registration_status.description = 'ATIVA'	cnpjEN
SELECT cnae.name, AVG(company.capital) FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE establishment.start_activity_date > '20151231' AND establishment.basic_cnpj IN (SELECT DISTINCT partner.basic_cnpj FROM partner JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE qualification.description = 'Administrador') GROUP BY cnae.name HAVING COUNT(DISTINCT company.basic_cnpj) > 3 ORDER BY AVG(company.capital) DESC	cnpjEN
SELECT city.name, COUNT(establishment.basic_cnpj) FROM establishment JOIN city ON establishment.city_code = city.code WHERE establishment.start_activity_date >= '20210101' GROUP BY city.name ORDER BY COUNT(establishment.basic_cnpj) DESC LIMIT 5	cnpjEN
SELECT company.name, cnae.name, registration_status_reason.description FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN registration_status_reason ON establishment.registration_status_reason_code = registration_status_reason.code WHERE establishment.state = 'SP'	cnpjEN
SELECT cnae.name, COUNT(establishment.basic_cnpj) FROM establishment JOIN cnae ON establishment.primary_cnae_code = cnae.code GROUP BY cnae.name ORDER BY COUNT(establishment.basic_cnpj) DESC LIMIT 5	cnpjEN
SELECT qualification.description, COUNT(partner.basic_cnpj), AVG(company.capital) FROM partner JOIN company ON partner.basic_cnpj = company.basic_cnpj JOIN qualification ON partner.partner_qualification_code = qualification.code GROUP BY qualification.description HAVING COUNT(partner.basic_cnpj) >= 10 ORDER BY COUNT(partner.basic_cnpj) DESC	cnpjEN
SELECT legal_nature.description, COUNT(*) FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'DEMAIS' GROUP BY legal_nature.description ORDER BY COUNT(*) DESC LIMIT 5	cnpjEN
SELECT company_size.description, AVG(company.capital) FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY company_size.description	cnpjEN
SELECT company.name, cnae.name FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN taxation ON company.basic_cnpj = taxation.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE taxation.option_for_simples_taxation = 'S' AND establishment.start_activity_date > '20151231'	cnpjEN
SELECT establishment.state, COUNT(*) FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY establishment.state ORDER BY COUNT(*) DESC LIMIT 5	cnpjEN
SELECT company.name, COUNT(*) FROM company JOIN partner ON company.basic_cnpj = partner.basic_cnpj JOIN qualification ON partner.partner_qualification_code = qualification.code WHERE qualification.description = 'Administrador' GROUP BY company.name	cnpjEN
SELECT legal_nature.description, AVG(company.capital) FROM company JOIN legal_nature ON company.legal_nature_code = legal_nature.code GROUP BY legal_nature.description ORDER BY AVG(company.capital) DESC LIMIT 5	cnpjEN
SELECT company.name, company.capital FROM company JOIN company_size ON company.company_size_code = company_size.code WHERE company_size.description = 'MICRO EMPRESA' ORDER BY company.capital DESC LIMIT 5	cnpjEN
SELECT qualification.description, COUNT(partner.basic_cnpj) FROM partner JOIN qualification ON partner.partner_qualification_code = qualification.code GROUP BY qualification.description ORDER BY COUNT(partner.basic_cnpj) DESC LIMIT 5	cnpjEN
SELECT legal_nature.description, COUNT(company.basic_cnpj) FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN legal_nature ON company.legal_nature_code = legal_nature.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY legal_nature.description ORDER BY COUNT(company.basic_cnpj) DESC	cnpjEN
SELECT company.name, COUNT(partner.cpf_or_cnpj) FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN partner ON company.basic_cnpj = partner.basic_cnpj WHERE company_size.description = 'MICRO EMPRESA' GROUP BY company.name ORDER BY COUNT(partner.cpf_or_cnpj) DESC	cnpjEN
SELECT company_size.description, COUNT(establishment.basic_cnpj) FROM establishment JOIN company ON establishment.basic_cnpj = company.basic_cnpj JOIN company_size ON company.company_size_code = company_size.code JOIN registration_status ON establishment.registration_status_code = registration_status.code WHERE registration_status.description = 'ATIVA' GROUP BY company_size.description ORDER BY COUNT(establishment.basic_cnpj) DESC	cnpjEN
SELECT cnae.name, COUNT(company.basic_cnpj), AVG(company.capital) FROM company JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE company.basic_cnpj IN (SELECT DISTINCT partner.basic_cnpj FROM partner JOIN qualification ON partner.partner_qualification_code = qualification.code JOIN establishment ON partner.basic_cnpj = establishment.basic_cnpj JOIN registration_status ON establishment.registration_status_code = registration_status.code JOIN taxation ON partner.basic_cnpj = taxation.basic_cnpj WHERE qualification.description = 'Sócio-Administrador' AND registration_status.description = 'ATIVA' AND taxation.option_for_simples_taxation = 'S') GROUP BY cnae.name HAVING COUNT(company.basic_cnpj) > 5 ORDER BY COUNT(company.basic_cnpj) DESC	cnpjEN
SELECT company_size.description, COUNT(partner.basic_cnpj) FROM partner JOIN company ON partner.basic_cnpj = company.basic_cnpj JOIN company_size ON company.company_size_code = company_size.code GROUP BY company_size.description ORDER BY COUNT(partner.basic_cnpj) DESC	cnpjEN
SELECT city.name, COUNT(*) FROM company JOIN company_size ON company.company_size_code = company_size.code JOIN establishment ON company.basic_cnpj = establishment.basic_cnpj JOIN city ON establishment.city_code = city.code WHERE company_size.description = 'DEMAIS' GROUP BY city.name ORDER BY COUNT(*) DESC LIMIT 5	cnpjEN
SELECT city.name, COUNT(establishment.basic_cnpj) FROM establishment JOIN city ON establishment.city_code = city.code GROUP BY city.name ORDER BY COUNT(establishment.basic_cnpj) DESC LIMIT 5	cnpjEN
SELECT cnae.name, COUNT(DISTINCT establishment.basic_cnpj), SUM(company.capital), COUNT(DISTINCT partner.cpf_or_cnpj) FROM establishment JOIN registration_status ON establishment.registration_status_code = registration_status.code JOIN partner ON establishment.basic_cnpj = partner.basic_cnpj JOIN country ON partner.country_code = country.code JOIN cnae ON establishment.primary_cnae_code = cnae.code JOIN company ON establishment.basic_cnpj = company.basic_cnpj WHERE registration_status.description = 'ATIVA' AND country.name != 'BRASIL' GROUP BY cnae.name ORDER BY COUNT(DISTINCT establishment.basic_cnpj) DESC LIMIT 3	cnpjEN
SELECT cnae.name, COUNT(establishment.basic_cnpj) FROM establishment JOIN city ON establishment.city_code = city.code JOIN cnae ON establishment.primary_cnae_code = cnae.code WHERE city.name = 'CURITIBA' GROUP BY cnae.name ORDER BY COUNT(establishment.basic_cnpj) DESC LIMIT 3	cnpjEN
